export const UPDATE_USERINFO = "UPDATE_USERINFO";
export const UPDATE_BOOKINFO = "UPDATE_BOOKINFO";
export const UPDATE_TODAYINFO = "UPDATE_TODAYINFO";
export const UPDATE_BOOKS = "UPDATE_BOOKS";
export const UPDATE_REVIEW = "UPDATE_REVIEW";
export const UPDATE_WORDS = "UPDATE_WORDS";
export const UPDATE_SECTION = "UPDATE_SECITON";
